// =================================================================================
// R2-UI-WORKER v3.7 (Interaction Enhanced by Gemini)
// Features: Light/Dark Mode, Image Previews, Lightbox, Grid/List View, Mobile-First.
// Changelog:
// - (Feature) Create & Move Interaction: After creating a folder, any pre-selected items will be automatically moved into it.
// - (Fix) Robust Move API: The backend /api/move endpoint now correctly handles moving non-empty folders and their contents.
// - Maintained original code structure and worker.js format as requested.
// =================================================================================

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname.startsWith('/api/')) {
      return this.handleApiRequest(request, env);
    }
    
    if (url.pathname.length > 1 && !url.pathname.startsWith('/api')) {
      return this.handleFileDownload(request, env);
    }
    
    // The main page is generated by this function
    return new Response(this.generateHTML(env.WORKER_NAME), {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    });
  },

  async handleApiRequest(request, env) {
    const url = new URL(request.url);
    const password = request.headers.get('x-auth-password');
    const { BUCKET, AUTH_PASSWORD } = env;

    if (!AUTH_PASSWORD || password !== AUTH_PASSWORD) {
      return new Response('Invalid Password', { status: 401 });
    }

    if (url.pathname === '/api/list' && request.method === 'GET') {
      const listing = await BUCKET.list({ limit: 1000, include: ['httpMetadata'] });
      return new Response(JSON.stringify(listing.objects), { headers: { 'Content-Type': 'application/json' } });
    }

    if (request.method === 'PUT' && url.pathname.startsWith('/api/upload/')) {
      const key = decodeURIComponent(url.pathname.substring('/api/upload/'.length));
      if (!key) return new Response('Filename missing.', { status: 400 });
      await BUCKET.put(key, request.body, { httpMetadata: request.headers });
      return new Response(`Uploaded ${key} successfully.`, { status: 201 });
    }

    if (request.method === 'POST' && url.pathname === '/api/delete') {
      try {
        const { keys } = await request.json();
        if (!Array.isArray(keys) || keys.length === 0) return new Response('Keys array is required.', { status: 400 });
        await BUCKET.delete(keys);
        return new Response(`Deleted ${keys.length} objects.`, { status: 200 });
      } catch (e) { return new Response('Invalid JSON format.', { status: 400 }); }
    }
    
    if (request.method === 'POST' && url.pathname === '/api/create-folder') {
        try {
            const { folderName } = await request.json();
            const trimmedName = folderName.trim();
            if (!trimmedName || trimmedName.includes('/')) {
                return new Response('Invalid folder name. It cannot be empty or contain slashes.', { status: 400 });
            }
            const key = `${trimmedName}/`;
            const existing = await BUCKET.head(key);
            if (existing) {
                return new Response('An object with this name already exists.', { status: 409 });
            }
            await BUCKET.put(key, null);
            return new Response(`Folder ${key} created successfully.`, { status: 201 });
        } catch (e) {
            return new Response('Invalid request: ' + e.message, { status: 400 });
        }
    }

    // MODIFIED: Enhanced logic to properly move folders and their contents.
    if (request.method === 'POST' && url.pathname === '/api/move') {
      try {
        const { oldKey, newKey } = await request.json();
        if (!oldKey || !newKey) return new Response('Both oldKey and newKey are required.', { status: 400 });
        if (oldKey === newKey) return new Response('Source and destination are the same.', { status: 400 });
        
        const isFolder = oldKey.endsWith('/');
        if (isFolder) {
            // Prevent moving a folder into itself
            if (newKey.startsWith(oldKey)) {
                return new Response('Invalid move. Cannot move a folder into itself.', { status: 400 });
            }

            // List all objects in the folder
            const list = await BUCKET.list({ prefix: oldKey, limit: 1000 }); // R2 list limit is 1000
            let objectsToMove = list.objects;

            // Handle empty folders which might not appear in the list
            if (objectsToMove.length === 0) {
                const emptyFolderObject = await BUCKET.head(oldKey);
                if (emptyFolderObject) {
                    objectsToMove = [{ key: oldKey, size: emptyFolderObject.size }];
                }
            }
            
            // If there's nothing to move, return success.
            if (objectsToMove.length === 0) {
                return new Response(`Folder ${oldKey} not found or is empty.`, { status: 200 });
            }
            
            // Batch copy all objects to the new location
            for (const obj of objectsToMove) {
                const objectToCopy = await BUCKET.get(obj.key);
                if (objectToCopy) {
                    const newObjectKey = newKey + obj.key.substring(oldKey.length);
                    await BUCKET.put(newObjectKey, objectToCopy.body, {
                        httpMetadata: objectToCopy.httpMetadata,
                        customMetadata: objectToCopy.customMetadata,
                    });
                }
            }
            
            // Batch delete all old objects
            const keysToDelete = objectsToMove.map(obj => obj.key);
            await BUCKET.delete(keysToDelete);
            
            return new Response(`Moved folder ${oldKey} to ${newKey} successfully.`, { status: 200 });

        } else {
            // Original logic for moving a single file
            const object = await BUCKET.get(oldKey);
            if (!object) return new Response('Object not found', { status: 404 });
            await BUCKET.put(newKey, object.body, { httpMetadata: object.httpMetadata, customMetadata: object.customMetadata });
            await BUCKET.delete(oldKey);
            return new Response(`Moved ${oldKey} to ${newKey} successfully.`, { status: 200 });
        }
      } catch (e) { return new Response('Error moving file: ' + e.message, { status: 500 }); }
    }

    return new Response('API endpoint not found.', { status: 404 });
  },

  async handleFileDownload(request, env) {
    const key = decodeURIComponent(new URL(request.url).pathname.slice(1));
    const object = await env.BUCKET.get(key);
    if (object === null) return new Response('Object Not Found', { status: 404 });
    
    // Do not allow downloading of zero-byte folder placeholder files
    if (object.size === 0 && key.endsWith('/')) {
        return new Response('This is a folder, not a downloadable file.', { status: 400 });
    }

    const headers = new Headers();
    object.writeHttpMetadata(headers);
    headers.set('etag', object.httpEtag);
    headers.set('cache-control', 'public, max-age=259200');
    return new Response(object.body, { headers });
  },

  /**
   * Generates the HTML for the front-end interface.
   * All front-end logic (HTML, CSS, client-side JS) is contained within this string.
   */
  generateHTML() {
    // NOTE: All backticks ` within the <script> tag are escaped as \` to be valid inside a JS template literal.
    return `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cloudflare-R2</title>
  <style>
    :root {
      --c-dark-bg: #1a1b26; --c-dark-card: #24283b; --c-dark-text: #c0caf5; --c-dark-text-light: #a9b1d6; --c-dark-border: #414868;
      --c-light-bg: #eff1f5; --c-light-card: #ffffff; --c-light-text: #4c4f69; --c-light-text-light: #5c5f77; --c-light-border: #ccd0da;
      --c-primary: #7aa2f7; --c-success: #9ece6a; --c-error: #f7768e; --c-accent: #bb9af7;
    }
    html[data-theme='dark'] {
      --bg-color: var(--c-dark-bg); --card-bg: var(--c-dark-card); --text-color: var(--c-dark-text); --text-light: var(--c-dark-text-light); --border-color: var(--c-dark-border);
    }
    html[data-theme='light'] {
      --bg-color: var(--c-light-bg); --card-bg: var(--c-light-card); --text-color: var(--c-light-text); --text-light: var(--c-light-text-light); --border-color: var(--c-light-border);
    }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; background-color: var(--bg-color); color: var(--text-color); font-size: 16px; transition: background-color .3s, color .3s; }
    .hidden { display: none !important; }
    #login-view { display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100vh; }
    .login-box { padding: 40px; background-color: var(--card-bg); border-radius: 12px; text-align: center; box-shadow: 0 10px 25px rgba(0,0,0,0.1); width: 90%; max-width: 350px; box-sizing: border-box; }
    .login-box h1 { color: var(--c-primary); margin-top: 0; }
    .login-box input { width: 100%; box-sizing: border-box; padding: 12px; margin: 10px 0; background-color: var(--bg-color); border: 1px solid var(--border-color); border-radius: 8px; color: var(--text-color); font-size: 1em; }
    .login-box button { width: 100%; padding: 12px; background-color: var(--c-primary); border: none; border-radius: 8px; color: #fff; font-size: 1.1em; cursor: pointer; }
    #login-error { color: var(--c-error); margin-top: 10px; height: 20px; }
    #app-view { padding: 15px; max-width: 1400px; margin: 0 auto; }
    header { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 15px; margin-bottom: 20px; }
    header h1 { color: var(--c-primary); margin: 0; font-size: 1.8em; }
    .actions { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }
    .actions button { background: var(--card-bg); color: var(--text-light); border: 1px solid var(--border-color); border-radius: 8px; padding: 10px 15px; cursor: pointer; transition: all 0.2s; font-size: 1em; }
    .actions button:hover { border-color: var(--c-primary); color: var(--c-primary); }
    #view-toggle-button { padding: 10px; line-height: 0; }
    #view-toggle-button svg { width: 20px; height: 20px; vertical-align: middle; }
    #delete-button { background-color: var(--c-error); color: #fff; border-color: var(--c-error); }
    #select-all-button { background-color: var(--c-success); color: #fff; border-color: var(--c-success); }
    .uploader { border: 2px dashed var(--border-color); border-radius: 12px; padding: 20px; text-align: center; cursor: pointer; margin-bottom: 20px; }
    .uploader.dragging { background-color: var(--c-primary); color: #fff; }
    .file-container.list-view { display: block; }
    .file-container.list-view .file-item { display: flex; align-items: center; padding: 10px; background-color: var(--card-bg); border-radius: 8px; margin-bottom: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); position: relative; }
    .list-view .icon { flex-shrink: 0; width: 20px; height: 20px; display:flex; align-items:center; justify-content:center; margin: 0 10px; }
    .list-view .icon svg, .grid-view .icon svg { width: 20px; height: 20px; color: var(--c-primary); }
    .list-view .info { flex-grow: 1; margin: 0 10px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .list-view .filename { font-weight: bold; }
    .list-view .filesize { font-size: 0.9em; color: var(--text-light); }
    .list-view .checkbox { margin-left: 0; margin-right: 10px; }
    .file-container.grid-view { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 15px; }
    .grid-view .file-item { position: relative; background: var(--card-bg); border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); border: 2px solid transparent; transition: transform 0.2s, border-color 0.2s; }
    .grid-view .file-item:hover { transform: translateY(-5px); }
    .grid-view .file-item.selected { border-color: var(--c-primary); transform: translateY(0) !important; }
    .grid-view .icon { height: 120px; display: flex; justify-content: center; align-items: center; background-color: rgba(0,0,0,0.1); }
    .grid-view .icon img { width: 100%; height: 100%; object-fit: cover; border-top-left-radius: 10px; border-top-right-radius: 10px; }
    .grid-view .info { padding: 15px; text-align: center; }
    .grid-view .filename { font-weight: bold; word-break: break-all; margin-bottom: 5px; }
    .grid-view .filesize { font-size: 0.8em; color: var(--text-light); }
    .grid-view .checkbox { position: absolute; bottom: 5px; left: 5px; z-index: 5; opacity: 0; transition: opacity .2s ease-in-out; }
    .grid-view .file-item:hover .checkbox, .grid-view .file-item.selected .checkbox { opacity: 1; }
    .checkbox { width: 20px; height: 20px; accent-color: var(--c-primary); cursor: pointer; }
    #lightbox { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.85); display: flex; justify-content: center; align-items: center; z-index: 1000; }
    #lightbox img { max-width: 90%; max-height: 90%; object-fit: contain; }
    .lightbox-nav { position: absolute; top: 50%; transform: translateY(-50%); background: rgba(0,0,0,0.5); color: #fff; border: none; font-size: 2em; padding: 10px 15px; cursor: pointer; border-radius: 8px; }
    #lightbox-prev { left: 20px; } #lightbox-next { right: 20px; } #lightbox-close { top: 20px; right: 20px; transform: none; font-size: 1.5em; }
    .theme-toggle { position: fixed; top: 10px; right: 10px; padding: 8px 12px; background-color: var(--card-bg); border: 1px solid var(--border-color); border-radius: 20px; cursor: pointer; z-index: 1000; font-size: 16px; }
    .theme-toggle:hover { background-color: var(--c-primary); color: #fff; }
    .list-view .file-actions { position: static; margin-left: auto; padding-left: 10px; }
    .list-view .menu-button { width: 20px; height: 20px; font-size: 14px; }
    .list-view .menu-items { bottom: auto; top: 30px; right: 0; }
    .grid-view .file-actions { position: absolute; bottom: 5px; right: 5px; z-index: 10; opacity: 0; transition: opacity 0.2s ease-in-out; }
    .grid-view .file-item:hover .file-actions, .grid-view .file-item.selected .file-actions { opacity: 1; }
    .menu-button { width: 20px; height: 20px; background-color: var(--card-bg); border-radius: 50%; display: flex; justify-content: center; align-items: center; cursor: pointer; opacity: 0.7; transition: opacity 0.3s; }
    .menu-button:hover { opacity: 1; background-color: var(--c-primary); color: white; }
    .menu-button::after { content: "⋮"; font-size: 16px; font-weight: bold; }
    .menu-items { position: absolute; bottom: 30px; right: 0; background-color: var(--card-bg); border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.2); z-index: 20; width: 120px; overflow: hidden; display: none; }
    .menu-items.show { display: block; }
    .menu-item { padding: 8px 12px; cursor: pointer; font-size: 14px; transition: background-color 0.2s; }
    .menu-item:hover { background-color: var(--c-primary); color: white; }
    .dialog { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: var(--card-bg); padding: 20px; border-radius: 8px; box-shadow: 0 4px 20px rgba(0,0,0,0.2); z-index: 2000; display: none; width: 90%; max-width: 400px; box-sizing: border-box; }
    .dialog.show { display: block; }
    .dialog h3 { margin-top: 0; color: var(--text-color); }
    .dialog input, .dialog select { width: 100%; box-sizing: border-box; padding: 10px; margin-bottom: 15px; border: 1px solid var(--border-color); border-radius: 4px; background-color: var(--bg-color); color: var(--text-color); }
    .dialog-buttons { display: flex; justify-content: flex-end; gap: 10px; }
    @media (max-width: 768px) {
      header { flex-direction: column; align-items: flex-start; gap: 20px; }
      .file-container.grid-view { grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); }
      .actions button, #view-toggle-button { padding: 8px 10px; font-size: 0.9em; }
    }
    @media (max-width: 480px) {
      .grid-view .icon { height: 100px; }
      .file-container.grid-view { grid-template-columns: repeat(auto-fill, minmax(120px, 1fr)); }
      .login-box { padding: 25px; }
    }
  </style>
</head>
<body>

  <button class="theme-toggle" id="global-theme-toggle"><span class="sun">☀️</span><span class="moon hidden">🌙</span></button>

  <div class="dialog" id="rename-dialog">
    <h3>重命名</h3><input type="text" id="new-filename" placeholder="新名称"><div class="dialog-buttons"><button id="rename-cancel">取消</button><button id="rename-confirm">确认</button></div>
  </div>
  
  <div class="dialog" id="create-folder-dialog">
    <h3>新建文件夹</h3><input type="text" id="new-folder-name" placeholder="文件夹名称 (不能包含'/')"><div class="dialog-buttons"><button id="create-folder-cancel">取消</button><button id="create-folder-confirm">确认</button></div>
  </div>
  
  <div class="dialog" id="move-dialog">
    <h3>移动项目</h3><p id="move-item-name" style="word-break: break-all; font-size: 0.9em; color: var(--text-light);"></p><label for="folder-destination">选择目标文件夹:</label><select id="folder-destination"></select><div class="dialog-buttons"><button id="move-cancel">取消</button><button id="move-confirm">确认</button></div>
  </div>

  <svg class="hidden"><defs>
    <symbol id="icon-grid-view" viewBox="0 0 24 24"><path fill="currentColor" d="M3 3h8v8H3V3zm10 0h8v8h-8V3zM3 13h8v8H3v-8zm10 13h8v-8h-8v8z"/></symbol>
    <symbol id="icon-list-view" viewBox="0 0 24 24"><path fill="currentColor" d="M3 4h18v2H3V4zm0 7h18v2H3v-2zm0 7h18v2H3v-2z"/></symbol>
    <symbol id="icon-folder" viewBox="0 0 24 24"><path fill="currentColor" d="M10 4H4c-1.11 0-2 .89-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8c0-1.11-.89-2-2-2h-8l-2-2z"/></symbol>
    <symbol id="icon-file" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zM6 20V4h7v5h5v11H6z"/></symbol>
    <symbol id="icon-video" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zM10 15.5v-5l4 2.5l-4 2.5zM6 20V4h7v5h5v11H6z"/></symbol>
    <symbol id="icon-audio" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zm-2 15a3 3 0 1 1 0-6a3 3 0 0 1 0 6zm0-8a1 1 0 0 0-1 1v2.55A3 3 0 0 0 9 14a3 3 0 0 0 6 0a3 3 0 0 0-2-2.82V9a1 1 0 0 0-1-1h-2zM6 20V4h7v5h5v11H6z"/></symbol>
    <symbol id="icon-zip" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zM9 18H7v-2h2v2zm0-4H7v-2h2v2zm0-4H7V8h2v2zm4 8h-2v-2h2v2zm0-4h-2v-2h2v2zm0-4h-2V8h2v2zm4 8h-2v-2h2v2zm0-4h-2v-2h2v2zM6 20V4h7v5h5v11H6z"/></symbol>
    <symbol id="icon-doc" viewBox="0 0 24 24"><path fill="currentColor" d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zM16 18H8v-2h8v2zm0-4H8v-2h8v2zm-3-4H8V8h5v2zM6 20V4h7v5h5v11H6z"/></symbol>
  </defs></svg>

  <div id="login-view"><div class="login-box"><h1>Cloudflare-R2</h1><input type="password" id="password-input" placeholder="请输入访问密码"><button id="login-button">进入</button><p id="login-error"></p></div></div>

  <div id="app-view" class="hidden">
    <header><h1>文件列表</h1><div class="actions"><button id="create-folder-button">新建文件夹</button><button id="view-toggle-button" title="切换视图"></button><button id="select-all-button">全选</button><button id="delete-button">删除选中</button></div></header>
    <input type="file" id="file-input" multiple class="hidden"><div class="uploader" id="drop-zone"><p>拖拽文件到此处，或点击上传</p></div>
    <div id="file-container"></div>
  </div>

  <div id="lightbox" class="hidden">
    <button id="lightbox-close" class="lightbox-nav">&times;</button><button id="lightbox-prev" class="lightbox-nav">&#10094;</button><button id="lightbox-next" class="lightbox-nav">&#10095;</button><img id="lightbox-image" src="" alt="Image preview">
  </div>

<script>
document.addEventListener('DOMContentLoaded', () => {
  const G = {
    loginView: document.getElementById('login-view'), appView: document.getElementById('app-view'), fileContainer: document.getElementById('file-container'),
    loginButton: document.getElementById('login-button'), deleteButton: document.getElementById('delete-button'), viewToggleButton: document.getElementById('view-toggle-button'), selectAllButton: document.getElementById('select-all-button'),
    passwordInput: document.getElementById('password-input'), fileInput: document.getElementById('file-input'), dropZone: document.getElementById('drop-zone'),
    lightbox: document.getElementById('lightbox'), lightboxImage: document.getElementById('lightbox-image'), lightboxClose: document.getElementById('lightbox-close'), lightboxPrev: document.getElementById('lightbox-prev'), lightboxNext: document.getElementById('lightbox-next'),
    themeToggle: document.getElementById('global-theme-toggle'),
    renameDialog: document.getElementById('rename-dialog'), newFilename: document.getElementById('new-filename'), renameCancel: document.getElementById('rename-cancel'), renameConfirm: document.getElementById('rename-confirm'),
    createFolderButton: document.getElementById('create-folder-button'), createFolderDialog: document.getElementById('create-folder-dialog'), newFolderName: document.getElementById('new-folder-name'), createFolderCancel: document.getElementById('create-folder-cancel'), createFolderConfirm: document.getElementById('create-folder-confirm'),
    moveDialog: document.getElementById('move-dialog'), moveItemName: document.getElementById('move-item-name'), folderDestination: document.getElementById('folder-destination'), moveCancel: document.getElementById('move-cancel'), moveConfirm: document.getElementById('move-confirm'),
    password: '', files: [], imageFiles: [], currentImageIndex: -1,
    theme: localStorage.getItem('theme') || 'dark', viewMode: localStorage.getItem('viewMode') || 'grid',
    isAllSelected: false, currentFileKey: null, currentMenu: null,
  };

  const showToast = (message, duration = 3000) => {
    let toast = document.getElementById('toast');
    if (!toast) {
      toast = document.createElement('div');
      toast.id = 'toast';
      Object.assign(toast.style, { position: 'fixed', bottom: '20px', left: '50%', transform: 'translateX(-50%)', backgroundColor: 'var(--c-accent)', color: '#fff', padding: '10px 20px', borderRadius: '8px', zIndex: '9999', opacity: '0', transition: 'opacity 0.3s' });
      document.body.appendChild(toast);
    }
    toast.textContent = message;
    toast.style.opacity = '1';
    setTimeout(() => { toast.style.opacity = '0'; }, duration);
  };
  
  const getFileIcon = (filename) => {
    if (filename.endsWith('/')) return '#icon-folder';
    const ext = filename.split('.').pop().toLowerCase();
    if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'].includes(ext)) return 'image';
    if (['mp4', 'mov', 'avi', 'webm', 'mkv'].includes(ext)) return '#icon-video';
    if (['mp3', 'wav', 'ogg', 'flac'].includes(ext)) return '#icon-audio';
    if (['zip', 'rar', '7z', 'tar', 'gz'].includes(ext)) return '#icon-zip';
    if (['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'md'].includes(ext)) return '#icon-doc';
    return '#icon-file';
  };
  
  const formatBytes = (bytes, d=2) => { if(!+bytes)return"0 Bytes";const i=Math.floor(Math.log(bytes)/Math.log(1024)); return \`\${parseFloat((bytes/Math.pow(1024,i)).toFixed(d))} \${"Bytes,KB,MB,GB,TB"[i]}\` };
  const apiCall = async (endpoint, options = {}) => { const headers = { 'x-auth-password': G.password, ...options.headers }; const response = await fetch(endpoint, { ...options, headers }); if (!response.ok) throw new Error(await response.text() || \`HTTP error! \${response.status}\`); return response; };
  const applyTheme = () => { document.documentElement.setAttribute('data-theme', G.theme); const sun = G.themeToggle.querySelector('.sun'); const moon = G.themeToggle.querySelector('.moon'); if (G.theme === 'dark') { sun.classList.add('hidden'); moon.classList.remove('hidden'); } else { sun.classList.remove('hidden'); moon.classList.add('hidden'); } };
  const toggleTheme = () => { G.theme = G.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('theme', G.theme); applyTheme(); };
  const applyViewMode = () => { G.fileContainer.className = \`file-container \${G.viewMode}-view\`; G.viewToggleButton.innerHTML = G.viewMode === 'grid' ? '<svg><use xlink:href="#icon-list-view"></use></svg>' : '<svg><use xlink:href="#icon-grid-view"></use></svg>'; renderFiles(); };
  const toggleViewMode = () => { G.viewMode = G.viewMode === 'grid' ? 'list' : 'grid'; localStorage.setItem('viewMode', G.viewMode); applyViewMode(); };
  const openLightbox = (index) => { G.currentImageIndex = index; G.lightboxImage.src = encodeURIComponent(G.imageFiles[G.currentImageIndex].key); G.lightbox.classList.remove('hidden'); document.body.style.overflow = 'hidden'; };
  const closeLightbox = () => { G.lightbox.classList.add('hidden'); document.body.style.overflow = 'auto'; };
  const showNextImage = () => openLightbox((G.currentImageIndex + 1) % G.imageFiles.length);
  const showPrevImage = () => openLightbox((G.currentImageIndex - 1 + G.imageFiles.length) % G.imageFiles.length);
  const getFolderList = () => {
    const folderSet = new Set(['/']); // Root folder
    G.files.forEach(file => {
        if (file.key.endsWith('/')) {
            folderSet.add(file.key);
        } else if (file.key.includes('/')) {
            folderSet.add(file.key.substring(0, file.key.lastIndexOf('/') + 1));
        }
    });
    return Array.from(folderSet).sort();
  };

  const renderFiles = () => {
    G.fileContainer.innerHTML = '';
    if (G.files.length === 0) { G.fileContainer.innerHTML = '<p style="text-align:center;color:var(--text-light);">存储桶为空。</p>'; return; }
    G.imageFiles = G.files.filter(f => getFileIcon(f.key) === 'image');
    // Sort folders first, then by upload date (newest first)
    const sortedFiles = [...G.files].sort((a, b) => {
        const aIsFolder = a.key.endsWith('/');
        const bIsFolder = b.key.endsWith('/');
        if (aIsFolder && !bIsFolder) return -1;
        if (!aIsFolder && bIsFolder) return 1;
        return new Date(b.uploaded) - new Date(a.uploaded);
    });

    sortedFiles.forEach(file => {
      const fileType = getFileIcon(file.key); const isImage = fileType === 'image'; const isFolder = fileType === '#icon-folder'; const item = document.createElement('div');
      item.className = \`file-item \${G.isAllSelected ? 'selected' : ''}\`; item.dataset.key = file.key;
      const iconHTML = isImage && G.viewMode === 'grid' ? \`<img src="/\${encodeURIComponent(file.key)}" alt="\${file.key}" loading="lazy">\` : \`<svg><use xlink:href="\${isFolder ? '#icon-folder' : (isImage ? '#icon-file' : fileType)}"></use></svg>\`;
      const actionsHTML = \`
        <div class="file-actions">
          <div class="menu-button" data-key="\${file.key}"></div>
          <div class="menu-items" data-key="\${file.key}">
            <div class="menu-item" data-action="rename">重命名</div>
            \${!isFolder ? '<div class="menu-item" data-action="download">下载</div>' : ''}
            <div class="menu-item" data-action="move">移动</div>
            \${!isFolder ? '<div class="menu-item" data-action="copy-link">复制链接</div>' : ''}
            <div class="menu-item" data-action="delete" style="color: var(--c-error);">删除</div>
          </div>
        </div>\`;
      item.innerHTML = (isImage && G.viewMode === 'grid') ? \`
        <div class="icon">\${iconHTML}</div>
        <div class="info"><div class="filename" title="\${file.key}">\${file.key}</div><div class="filesize">\${formatBytes(file.size)}</div></div>
        <input type="checkbox" class="checkbox" data-key="\${file.key}" \${G.isAllSelected ? 'checked' : ''}>\${actionsHTML}\` : \`
        <input type="checkbox" class="checkbox" data-key="\${file.key}" \${G.isAllSelected ? 'checked' : ''}>
        <div class="icon">\${iconHTML}</div>
        <div class="info"><div class="filename" title="\${file.key}">\${file.key}</div><div class="filesize">\${isFolder ? '文件夹' : formatBytes(file.size)}</div></div>
        \${actionsHTML}\`;
      G.fileContainer.appendChild(item);
    });
  };

  const handleFileAction = (action, key) => {
    G.currentFileKey = key;
    switch(action) {
      case 'rename': G.newFilename.value = key.endsWith('/') ? key.slice(0, -1) : key.split('/').pop(); G.renameDialog.classList.add('show'); break;
      case 'download': const a = document.createElement('a'); a.href = \`/\${encodeURIComponent(key)}\`; a.download = key; document.body.appendChild(a); a.click(); document.body.removeChild(a); break;
      case 'move':
        const folders = getFolderList();
        G.folderDestination.innerHTML = '';
        folders.forEach(folder => {
            const option = document.createElement('option');
            option.value = folder;
            option.textContent = folder === '/' ? '(根目录)' : folder;
            G.folderDestination.appendChild(option);
        });
        G.moveItemName.textContent = \`移动: \${key}\`;
        G.moveDialog.classList.add('show');
        break;
      case 'copy-link': navigator.clipboard.writeText(\`\${window.location.origin}/\${encodeURIComponent(key)}\`).then(() => showToast('链接已复制')).catch(err => showToast('复制失败: ' + err)); break;
      case 'delete': if (confirm(\`确定删除 "\${key}" 吗？\`)) { handleDelete([key]); } break;
    }
  };
  
  // MODIFIED: Refactored to be a pure API wrapper that throws on error.
  const moveOrRenameFile = async (oldKey, newKey) => {
      if (!newKey || newKey === oldKey) { return; }
      // This function now only makes the API call and relies on the calling function for feedback and list refresh.
      await apiCall('/api/move', { 
          method: 'POST', 
          headers: { 'Content-Type': 'application/json' }, 
          body: JSON.stringify({ oldKey, newKey }) 
      });
  };

  // MODIFIED: Added try/catch and user feedback via toasts.
  const handleRename = async () => {
      const oldKey = G.currentFileKey;
      const newName = G.newFilename.value.trim();
      G.renameDialog.classList.remove('show');
      if (!newName) return;
      
      const isFolder = oldKey.endsWith('/');
      const path = oldKey.includes('/') ? oldKey.substring(0, oldKey.lastIndexOf('/') + 1) : '';
      const newKey = path + newName + (isFolder ? '/' : '');

      try {
          await moveOrRenameFile(oldKey, newKey);
          showToast(\`操作成功: "\${newKey}"\`);
          await refreshFileList();
      } catch(error) {
          showToast(\`操作失败: \${error.message}\`);
      }
  };
  
  // MODIFIED: Added try/catch and user feedback via toasts.
  const handleMove = async () => {
    const oldKey = G.currentFileKey;
    const destination = G.folderDestination.value;
    G.moveDialog.classList.remove('show');

    const isFolder = oldKey.endsWith('/');
    const filename = isFolder ? oldKey.slice(0, -1).split('/').pop() + '/' : oldKey.split('/').pop();
    const newKey = (destination === '/') ? filename : destination + filename;

    try {
      await moveOrRenameFile(oldKey, newKey);
      showToast(\`成功移动到: "\${newKey}"\`);
      await refreshFileList();
    } catch (error) {
      showToast(\`移动失败: \${error.message}\`);
    }
  };
  
  // MODIFIED: Now checks for selected files and moves them into the new folder after creation.
  const handleCreateFolder = async () => {
    const folderName = G.newFolderName.value.trim();
    G.createFolderDialog.classList.remove('show');
    if (!folderName || folderName.includes('/')) {
        showToast('创建失败: 文件夹名称无效。');
        return;
    }

    const selectedKeys = Array.from(document.querySelectorAll('.checkbox:checked')).map(cb => cb.dataset.key);

    try {
      // 1. Create the folder
      await apiCall('/api/create-folder', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ folderName }) });
      
      // 2. If items were selected, move them into the new folder
      if (selectedKeys.length > 0) {
        showToast(\`文件夹 "\${folderName}" 创建成功。正在移动 \${selectedKeys.length} 个项目...\`);
        const destinationFolder = \`\${folderName}/\`;
        
        const movePromises = selectedKeys.map(oldKey => {
            const isFolder = oldKey.endsWith('/');
            const baseName = isFolder ? oldKey.slice(0, -1).split('/').pop() + '/' : oldKey.split('/').pop();
            const newKey = destinationFolder + baseName;
            return moveOrRenameFile(oldKey, newKey);
        });

        await Promise.all(movePromises);
        showToast(\`成功移动 \${selectedKeys.length} 个项目到 "\${folderName}"\`);
      } else {
        showToast(\`文件夹 "\${folderName}" 创建成功\`);
      }
      
      G.newFolderName.value = ''; // Clear input for next time
      await refreshFileList();
    } catch(error) {
        showToast('操作失败: ' + error.message);
    }
  };

  const toggleSelectAll = () => {
    G.isAllSelected = !G.isAllSelected;
    document.querySelectorAll('.file-item').forEach(item => {
      item.classList.toggle('selected', G.isAllSelected);
      const checkbox = item.querySelector('.checkbox');
      if (checkbox) checkbox.checked = G.isAllSelected;
    });
    G.selectAllButton.textContent = G.isAllSelected ? '取消全选' : '全选';
  };

  const refreshFileList = async () => {
    try { const response = await apiCall('/api/list'); G.files = await response.json(); G.isAllSelected = false; G.selectAllButton.textContent = '全选'; renderFiles(); }
    catch (error) { console.error(error); showToast('刷新列表失败'); }
  };
  
  const handleLogin = async () => {
    const pw = G.passwordInput.value; if (!pw) return;
    G.password = pw; G.loginButton.textContent = "验证中..."; G.loginButton.disabled = true;
    try { await apiCall('/api/list'); G.loginView.classList.add('hidden'); G.appView.classList.remove('hidden'); sessionStorage.setItem('r2-password', pw); await refreshFileList(); }
    catch (error) { document.getElementById('login-error').textContent = '密码错误'; setTimeout(()=> document.getElementById('login-error').textContent = '', 3000); }
    finally { G.loginButton.textContent = "进入"; G.loginButton.disabled = false; }
  };
  
  const handleUpload = async (files) => {
    showToast(\`开始上传 \${files.length} 个文件...\`);
    const uploadPromises = Array.from(files).map(file => apiCall(\`/api/upload/\${encodeURIComponent(file.name)}\`, { method: 'PUT', body: file }));
    try { await Promise.all(uploadPromises); showToast('所有文件上传成功！'); } catch(error) { showToast(\`上传失败: \${error.message}\`); }
    await refreshFileList();
  };

  const handleDelete = async (keys) => {
    if (!keys || keys.length === 0) keys = Array.from(document.querySelectorAll('.checkbox:checked')).map(cb => cb.dataset.key);
    if (keys.length === 0) { showToast("请先选择要删除的项目"); return; }
    if (!confirm(\`你确定要删除选中的 \${keys.length} 个项目吗？此操作不可恢复。\`)) return;
    try {
        await apiCall('/api/delete', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ keys }) });
        showToast(\`成功删除 \${keys.length} 个项目\`);
        await refreshFileList();
    } catch (error) { showToast(\`删除失败: \${error.message}\`); }
  };

  const setupEventListeners = () => {
    G.themeToggle.addEventListener('click', toggleTheme);
    G.loginButton.addEventListener('click', handleLogin);
    G.passwordInput.addEventListener('keypress', e => e.key === 'Enter' && handleLogin());
    G.deleteButton.addEventListener('click', () => handleDelete());
    G.createFolderButton.addEventListener('click', () => { G.newFolderName.value = ''; G.createFolderDialog.classList.add('show'); });
    G.selectAllButton.addEventListener('click', toggleSelectAll);
    G.viewToggleButton.addEventListener('click', toggleViewMode);
    G.dropZone.addEventListener('click', () => G.fileInput.click());
    G.fileInput.addEventListener('change', () => handleUpload(G.fileInput.files));
    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(e => document.body.addEventListener(e, p => p.preventDefault()));
    ['dragenter', 'dragover'].forEach(eventName => G.dropZone.addEventListener(eventName, () => G.dropZone.classList.add('dragging')));
    ['dragleave', 'drop'].forEach(eventName => G.dropZone.addEventListener(eventName, () => G.dropZone.classList.remove('dragging')));
    G.dropZone.addEventListener('drop', e => handleUpload(e.dataTransfer.files));
    G.lightboxClose.addEventListener('click', closeLightbox);
    G.lightboxPrev.addEventListener('click', showPrevImage);
    G.lightboxNext.addEventListener('click', showNextImage);
    document.addEventListener('keydown', e => { if (!G.lightbox.classList.contains('hidden')) { if (e.key === 'Escape') closeLightbox(); if (e.key === 'ArrowLeft') showPrevImage(); if (e.key === 'ArrowRight') showNextImage(); } });
    G.renameCancel.addEventListener('click', () => G.renameDialog.classList.remove('show'));
    G.renameConfirm.addEventListener('click', handleRename);
    G.createFolderCancel.addEventListener('click', () => G.createFolderDialog.classList.remove('show'));
    G.createFolderConfirm.addEventListener('click', handleCreateFolder);
    G.moveCancel.addEventListener('click', () => G.moveDialog.classList.remove('show'));
    G.moveConfirm.addEventListener('click', handleMove);

    G.fileContainer.addEventListener('click', e => {
        const target = e.target;
        const fileItem = target.closest('.file-item');
        if (!fileItem) return;
        const key = fileItem.dataset.key;
        
        if (target.matches('.checkbox')) {
            fileItem.classList.toggle('selected', target.checked);
            G.isAllSelected = document.querySelectorAll('.checkbox:checked').length === G.files.length;
            G.selectAllButton.textContent = G.isAllSelected ? '取消全选' : '全选';
            return;
        }
        
        if (target.matches('.menu-button')) {
            e.stopPropagation();
            const menu = fileItem.querySelector('.menu-items');
            if (G.currentMenu && G.currentMenu !== menu) G.currentMenu.classList.remove('show');
            menu.classList.toggle('show');
            G.currentMenu = menu;
            return;
        }

        if(target.closest('.menu-item')) {
            e.stopPropagation();
            const action = target.closest('.menu-item').dataset.action;
            if (action) {
                handleFileAction(action, key);
                target.closest('.menu-items').classList.remove('show');
                G.currentMenu = null;
            }
            return;
        }

        if (getFileIcon(key) === 'image') {
            const imageIndex = G.imageFiles.findIndex(f => f.key === key);
            if (imageIndex > -1) openLightbox(imageIndex);
        }
    });
    
    document.addEventListener('click', (e) => {
        if (G.currentMenu && !e.target.closest('.menu-button')) {
            G.currentMenu.classList.remove('show');
            G.currentMenu = null;
        }
    });
  };
  
  const init = () => {
    applyTheme(); applyViewMode(); setupEventListeners();
    const savedPassword = sessionStorage.getItem('r2-password');
    if (savedPassword) { G.passwordInput.value = savedPassword; handleLogin(); }
  };
  
  init();
});
</script>
</body>
</html>
`;
  }
};
